version: "2"

services:

  wifi-connect:
    network_mode: "host"
    privileged: true
    build: wifi-connect/.
    volumes:
      - /run/dbus:/host/run/dbus:ro
    labels:
      io.balena.features.dbus: "1"

  train-departure-display:
    restart: always
    privileged: true
    build: train-departure-display/.
